library(tidyverse)
library(ggrepel)
library(readxl)
library(cowplot)
library(ggokabeito)




# Load sample info --------------------------------------------------------

# these are in the same order as the BAMlist used for running pcangsd
samples <- read_csv("raw_data/genetics/samples_info.csv")


# Import the covariance matrix
# Generated by the snakemake pipeline
# May need to change the path based on your file system.  properly. 
cov_file <- "genomics/results/pcangsd/95ind_10X_filter/pca_genome_wide_GL_all_samples.cov"

C <- as.matrix(read.table(cov_file))
# Eigenvalues and eigenvectors
e <- eigen(C)

e$values/sum(e$values) # use PC1 and PC2 PVEs for the axis labels

pcs <- as_tibble(e$vectors) %>% 
  rename_with(str_replace, pattern = "V", replacement = "PC") 

pca_res <- bind_cols(samples, pcs) %>% 
  mutate(state = ifelse(state == "Colorado", "CO", state)) %>%
  mutate(state = ifelse(state == "utah", "UT", state))


# Make and save plot
ggplot(aes(x = PC1, y = PC2, color = state, label = sample), data = pca_res) +
  geom_point(size = 1, alpha = 0.8) +
  theme_cowplot() +
  scale_color_okabe_ito() +
  xlab("PC1- 6.34%") +
  ylab("PC2- 1.19%") +
  theme(legend.position = c(0.05, 0.08),
        legend.direction = "horizontal",
        legend.box.background = element_blank(),
        legend.background = element_blank(),
        legend.key.size = unit(2.5, "mm"),
        legend.title = element_text(size = 5, margin = margin(0,0,0,0, "mm")),
        legend.text = element_text(size = 5, margin = margin(0,0,0,0, "mm")),
        axis.title = element_text(size = 5, margin = margin(0,0,0,0, "mm")),
        axis.text = element_text(size = 5, margin = margin(0,0,0,0, "mm")),
        axis.line = element_line(size = 0.5),
        plot.margin = unit(c(1, 1, 1, 1), "mm"))
ggsave(filename = "genomics/results/figures/supplemental/genomic_pca_by_state.pdf", height = 50, width = 60, units = "mm")
