jobs: 9
resources: [cpus=1, nodes=1, cores=1]
local-cores: 1
cluster: "sbatch --partition=good_lab_cpu --cpus-per-task={resources.cpus} --output=/home/tt164677e/tim_beegfs/wtjr_sdm/logs/snakemake_slurm/%x_%j.out --mail-type=ALL --mail-user=timothy.j.thurman@gmail.com"
jobname: sm_wtjr_{rulename}_{jobid}.sh
latency-wait: 15
verbose: true
