

# Links generated by their web service
# All giving me 404s
# 2080, RCP 2.6, 2.5 arcmin
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/giss_e2_r/2_5min/giss_e2_r_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip

# 2080, RCP 4.5, 2.5 arcmin
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/giss_e2_r/2_5min/giss_e2_r_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip

# 2080, RCP 6.0, 2.5 arcmin
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/giss_e2_r/2_5min/giss_e2_r_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip


# Replacement they suggested in the past
http://gisweb.ciat.cgiar.org/ccafs_climate/files/data/ipcc_5ar_ciat_downscaled/rcp8_5/2070s/mri_cgcm3/30s/mri_cgcm3_rcp8_5_2070s_bio_30s_r1i1p1_no_tile_asc.zip
http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp8_5/2070s/mri_cgcm3/30s/mri_cgcm3_rcp8_5_2070s_bio_30s_r1i1p1_no_tile_asc.zip

# Attempt at new links
# Just find and replace
# Seems to be working
# Comment out when done
# 2080, RCP 2.6, 2.5 arcmin
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/giss_e2_r/2_5min/giss_e2_r_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp2_6/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp2_6_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip

# 2080, RCP 4.5, 2.5 arcmin
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/giss_e2_r/2_5min/giss_e2_r_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp4_5/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp4_5_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip

# 2080, RCP 6.0, 2.5 arcmin
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/gfdl_cm3/2_5min/gfdl_cm3_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/giss_e2_r/2_5min/giss_e2_r_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/ipsl_cm5a_lr/2_5min/ipsl_cm5a_lr_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/mri_cgcm3/2_5min/mri_cgcm3_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip
# http://datacgiar.s3.amazonaws.com/ccafs/ccafs-climate/data/ipcc_5ar_ciat_downscaled/rcp6_0/2080s/ncar_ccsm4/2_5min/ncar_ccsm4_rcp6_0_2080s_bio_2_5min_r1i1p1_no_tile_asc.zip



# Then, compile the model averages for each RCP scenario
# Template for all scenarios
template <- brick("processed_data/bioclim_30arcsec_for_WTJR_SDM.tif")

# RCP 2.6
base_dir <- "raw_data/worldclim_projections_2080s_other_RCPs/RCP_2_6/"
# Loop over bioclim variables (need 2 and 3)
# Then loop over folders within the base directory
for (bioclim_var in paste0("bio_", 2:3)) { # For each bioclim variable
  x <- list() # set up a list of results
  i <- 1
  for (folder in list.files(base_dir)) { # loop over the 5 folders containing the projections from the 5 models
    layer <- raster(x = file.path(base_dir, folder, paste0(bioclim_var, ".asc"))) # grab the raster of the right bioclim layer
    crop_layer <- crop(layer, y = template)
    x[[i]] <- crop_layer # add it to the list
    i <- i + 1
    rm(layer, crop_layer)
  }
  all_models_cropped <- stack(x) # then convert list to a raster stack
  model_avg <- calc(x = all_models_cropped, fun = mean, na.rm = T) # take the model averaged mean
  assign(x = eval(bioclim_var), value = model_avg) # and assign it to an object named according to the bioclim variable
} 

# Combine into rasterstack
stacked <- stack(bio_2, bio_3)

# And save
writeRaster(x = stacked, filename = "processed_data/bc23_CMIP5_RCP26_2080s_5modavg.grd", overwrite = T)

rm(list = ls())

# RCP 4.5
template <- brick("processed_data/bioclim_30arcsec_for_WTJR_SDM.tif")
base_dir <- "raw_data/worldclim_projections_2080s_other_RCPs/RCP_4_5/"
# Loop over bioclim variables (need 2 and 3)
# Then loop over folders within the base directory
for (bioclim_var in paste0("bio_", 2:3)) { # For each bioclim variable
  x <- list() # set up a list of results
  i <- 1
  for (folder in list.files(base_dir)) { # loop over the 5 folders containing the projections from the 5 models
    layer <- raster(x = file.path(base_dir, folder, paste0(bioclim_var, ".asc"))) # grab the raster of the right bioclim layer
    crop_layer <- crop(layer, y = template)
    x[[i]] <- crop_layer # add it to the list
    i <- i + 1
    rm(layer, crop_layer)
  }
  all_models_cropped <- stack(x) # then convert list to a raster stack
  model_avg <- calc(x = all_models_cropped, fun = mean, na.rm = T) # take the model averaged mean
  assign(x = eval(bioclim_var), value = model_avg) # and assign it to an object named according to the bioclim variable
} 

# Combine into rasterstack
stacked <- stack(bio_2, bio_3)

# And save
writeRaster(x = stacked, filename = "processed_data/bc23_CMIP5_RCP45_2080s_5modavg.grd", overwrite = T)

rm(list = ls())

# RCP 6.0
template <- brick("processed_data/bioclim_30arcsec_for_WTJR_SDM.tif")
base_dir <- "raw_data/worldclim_projections_2080s_other_RCPs/RCP_6_0/"
# Loop over bioclim variables (need 2 and 3)
# Then loop over folders within the base directory
for (bioclim_var in paste0("bio_", 2:3)) { # For each bioclim variable
  x <- list() # set up a list of results
  i <- 1
  for (folder in list.files(base_dir)) { # loop over the 5 folders containing the projections from the 5 models
    layer <- raster(x = file.path(base_dir, folder, paste0(bioclim_var, ".asc"))) # grab the raster of the right bioclim layer
    crop_layer <- crop(layer, y = template)
    x[[i]] <- crop_layer # add it to the list
    i <- i + 1
    rm(layer, crop_layer)
  }
  all_models_cropped <- stack(x) # then convert list to a raster stack
  model_avg <- calc(x = all_models_cropped, fun = mean, na.rm = T) # take the model averaged mean
  assign(x = eval(bioclim_var), value = model_avg) # and assign it to an object named according to the bioclim variable
} 

# Combine into rasterstack
stacked <- stack(bio_2, bio_3)

# And save
writeRaster(x = stacked, filename = "processed_data/bc23_CMIP5_RCP60_2080s_5modavg.grd", overwrite = T)


rm(list = ls())

# Then, look at correlations between RCP scenarios:
rcp26 <- brick("processed_data/bc23_CMIP5_RCP26_2080s_5modavg.grd")
rcp45 <- brick("processed_data/bc23_CMIP5_RCP45_2080s_5modavg.grd")
rcp60 <- brick("processed_data/bc23_CMIP5_RCP60_2080s_5modavg.grd")
rcp85 <- brick("processed_data/bc23_CMIP5_RCP85_2080s_5modavg.grd") %>% 
  aggregate(x = ., fact = 5)


# Combine bc2 values (the first layer of each stack, first col of the values() matrix)
bc2 <- cbind(values(rcp26)[,1],
             values(rcp45)[,1],
             values(rcp60)[,1],
             values(rcp85)[,1])

# And then get all pairwise correlations
cor(bc2, use = "pairwise")
cor(bc2, use = "complete")
cor(bc2, use = "pairwise", method = "spear")
cor(bc2, use = "complete", method = "spear")


# Then, bc3 values (second layer of each stack, second col of the values() matrix)
bc3 <- cbind(values(rcp26)[,2],
             values(rcp45)[,2],
             values(rcp60)[,2],
             values(rcp85)[,2])

# And then get all pairwise correlations
cor(bc3, use = "pairwise")
cor(bc3, use = "complete")
cor(bc3, use = "pairwise", method = "spear")
cor(bc3, use = "complete", method = "spear")

# can, can look at it visually as well:
plot(rcp26, main = "RCP 2.6")
plot(rcp45, main = "RCP 4.5")
plot(rcp60, main = "RCP 6.0")
plot(rcp85, main = "RCP 8.5")



